<?php

namespace Tests\Feature;

use App\Role;
use App\User;
use Faker\Factory;
use Tests\RestoreDatabaseTrait;
use Tests\TestCase;
use Illuminate\Support\Facades\Artisan;
use Tymon\JWTAuth\Facades\JWTAuth;


class UserTenantTest extends TestCase
{

    use RestoreDatabaseTrait;

    protected $data = [];

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Artisan::call('db:seed', [
            '--class'   => 'DatabaseSeeder',
            '--force'   => true
        ]);

        $faker = Factory::create();

        $this->data = [
            'name' => $faker->name,
            'email' => $faker->email,
            'active' => true,
            'password' => 'secret',
            'password_confirmation' => 'secret',
        ];

    }

    public function testUserCreate()
    {

        $data = $this->data;
        $data['roles'] = Role::TENANT_ADMIN;

        $user = User::first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $response = $this->post(route('users.tenants.store'), $data, $headers)
            ->assertStatus(200);


        $this->assertDatabaseHas('users', [
            'name' => $data['name'],
            'email' => $data['email'],
        ]);

        $response->assertJsonStructure([
            'data' => [
                'HTTP_Authorization'
            ]
        ]);

    }

    public function testShowUser()
    {

        $user = User::first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $response = $this->get(route('users.tenants.show', $user->id), $headers)
            ->assertStatus(200);

        $response->assertJson([
            'data' => [
                '_id' => $user->id,
                'userUuid' => $user->uuid,
                'name' => $user->name,
                'email' => $user->email,
            ]
        ]);

    }

    public function testAllUsersTenants()
    {

        $user = User::first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $response = $this->get(route('users.tenants.index'), $headers)
            ->assertStatus(200);

        $response->assertJsonStructure([
            'data' => [

                '*' => [
                    '_id',
                    'userUuid',
                    'name',
                    'email',
                    'active',
                ]

            ]

        ]);

        // $response->assertJson([
        //     'data' => [
        //         ['is_tenant' => User::TENANT_USER]
        //     ]
        // ]);

    }

    public function testUpdateUserNoPassword()
    {

        $user = User::first();

        $data = [
            'name' => str_random(12),
            'email' => $user->email
        ];

        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $this->put(route('users.tenants.update', $user->id), $data, $headers)
            ->assertStatus(200);

        $this->assertDatabaseMissing('users', [
            '_id' => $user->id,
            'name' => $user->name,
            'email' => $user->email,
        ]);

    }

    public function testUpdateUserWithPassword()
    {

        $data = [
            'name' => str_random(12),
            'email' => str_random(7) . '@mail.com',
            'password' => 123456,
            'password_confirmation' => 123456
        ];

        $user = User::first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $this->put(route('users.tenants.update', $user->id), $data, $headers)
            ->assertStatus(200);

        $this->assertDatabaseMissing('users', [
            '_id' => $user->id,
            'name' => $user->name,
            'email' => $user->email,
        ]);

    }

    public function testRestoreDatabase()
    {
        $this->restoreDatabase();
        $this->assertTrue(true);
    }

}
