<?php

namespace Tests\Feature;

use App\Entities\Role;
use App\Entities\User;
use Illuminate\Support\Facades\Artisan;
use Tests\RestoreDatabaseTrait;
use Tests\TestCase;
use Tymon\JWTAuth\Facades\JWTAuth;

class RoleAdminTest extends TestCase
{

    use RestoreDatabaseTrait;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testRolesAdminAll()
    {

        Artisan::call('db:seed', [
            '--class'   => 'PrivilegeSeeder',
            '--force'   => true
        ]);

        Artisan::call('db:seed', [
            '--class'   => 'RoleAdminSeeder',
            '--force'   => true
        ]);

        Artisan::call('db:seed', [
            '--class'   => 'UserAdminSeeder',
            '--force'   => true
        ]);



        $user = User::where('isAdmin', User::ADMIN_USER)->first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $response = $this->get(route('roles.admins.index'), $headers)
            ->assertStatus(200);

        $response->assertJsonStructure([
            '*' => [
                '_id',
                'name',
                'description',
                'uuid',
                'default',
                'privileges'
            ]

        ]);

        $response->assertJson([
            [
                'default' => true
            ]
        ]);

    }


    public function testShowRolesAdmin()
    {

        $user = User::where('isAdmin', User::ADMIN_USER)->first();
        $token = JWTAuth::fromUser($user);

        $headers = [
            'Accept' => 'application/vnd.laravel.v1+json',
            'HTTP_Authorization' => 'Bearer ' . $token
        ];

        $role = Role::whereIn('name', [
            Role::ADMIN
        ])->first();

        $response = $this->get(route('roles.admins.show', $role->id), $headers)
            ->assertStatus(200);

        $response->assertJson([
            'data' => [
                '_id' => $role->id,
                'name' => Role::ADMIN,
                'default' => true
            ]
        ]);

    }

    public function testRestoreDatabase()
    {
        $this->restoreDatabase();
        $this->assertTrue(true);
    }

}
