<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class RoleRegularTest extends TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


        //factory(User::class)->create(['is_admin' => User::ADMIN_USER]);

        Artisan::call('db:seed', [
            '--class'   => 'RoleRegularSeeder',
            '--force'   => true
        ]);

    }

    public function testRolesAdminAll()
    {
        $this->assertTrue(true);

    }

}
